Import Numpy Library in Python

In [1]:
import numpy as np

Creating 1D Array

In [2]:
array_1D = np.array([1,2,3])
array_1D

array([1, 2, 3])

Creating 2D Array

In [3]:
array_2D = np.array([[1,2,3],[4,5,6]])
array_2D

array([[1, 2, 3],
       [4, 5, 6]])

Create Array with 0 Values



In [4]:
zeroes_array = np.zeros((2,3))
zeroes_array

array([[0., 0., 0.],
       [0., 0., 0.]])

Create Array with 1's Values

In [5]:
ones_array = np.ones((4,4))
ones_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Creat Identity Array

In [6]:
indentity_array = np.identity(3)
indentity_array

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

For Loop in Array

In [7]:
range_array = np.arange(2,10,2)
range_array

array([2, 4, 6, 8])

Array copy using shalow copy tecnique

In [8]:
copy_array = range_array.copy()
copy_array

array([2, 4, 6, 8])

Check rows and column of this array

In [9]:
array_2D.shape

(2, 3)

Create 3D Array

In [10]:
array_3D = np.array([[[2,6],[9,6]],[[4,8],[1,7]]])
array_3D

array([[[2, 6],
        [9, 6]],

       [[4, 8],
        [1, 7]]])

Check Dimention of the Array

In [11]:
array_3D.ndim

3

Check Size of the Array

In [12]:
array_3D.size

8

Change Shape of the Array

In [13]:
reshape_array = np.arange(24)
reshape_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [14]:
reshape_array = reshape_array.reshape(6,4)
# reshape_array = reshape_array.reshape(2,12)
reshape_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [15]:
reshape_array[1:4,1:3]

array([[ 5,  6],
       [ 9, 10],
       [13, 14]])

Change Any n Dimentional Array into vector

In [16]:
array_2D.ravel()

array([1, 2, 3, 4, 5, 6])

Iteration in Arrays

In [17]:
for i in array_2D:
  print(i)

[1 2 3]
[4 5 6]


In [18]:
for i in np.nditer(array_2D):
  print(i)

1
2
3
4
5
6


Find Minimum Value from Array

In [19]:
print(array_1D)
array_1D.min()

[1 2 3]


1

Find Maximum Value from Array

In [20]:
print(array_2D)
array_2D.max()

[[1 2 3]
 [4 5 6]]


6

Statistical Functions in Array

In [21]:
array_1D.mean()

2.0

In [22]:
array_2D.std()

1.707825127659933

In [23]:
np.median(array_3D)

6.0

In [24]:
np.sin(reshape_array)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721],
       [ 0.91294525,  0.83665564, -0.00885131, -0.8462204 ]])

In [25]:
print(array_2D)
array_2D.transpose()

[[1 2 3]
 [4 5 6]]


array([[1, 4],
       [2, 5],
       [3, 6]])